### ISSUE TITLE
Implement login system with JSON web token

### ISSUE THREAD

**Issue by pckv** [pckv/kompis#15]
service and controller will need the following functionality:

- Create user
- Login, which adds the JSON web token as a response and returns the user object
- Get the current logged in user 
- Logout?

**Comment by Bromle** [comment]
https://medium.com/better-programming/secure-a-spring-boot-rest-api-with-json-web-token-reference-to-angular-integration-e57a25806c50

**Comment by pckv** [comment]
vi bruker https://auth0.com/blog/implementing-jwt-authentication-on-spring-boot/
