### ISSUE TITLE
Delete users listings when deleting a user

### ISSUE THREAD

**Issue by EspenK** [pckv/kompis#45]
When a user is deleted all their listings must be deleted as well. At the moment deleting a user with existing listings results in foreign key constraint.

**Comment by JesseWeHaveToCook** [comment]
Hello, can I take this issue? I think I have a solution for this.

**Comment by EspenK** [comment]
That would be very much appreciated, thank you Jesse.

**Comment by JesseWeHaveToCook** [comment]
#56

**Comment by JesseWeHaveToCook** [comment]
Thank you for assingning me, I've already made a pull request. #56
